version: '3.9'

services:
  app:
    build: .
    container_name: otp-auth-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: otp-postgres
    environment:
      POSTGRES_USER: otp_user
      POSTGRES_PASSWORD: otp_pass
      POSTGRES_DB: otp_auth_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: otp-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
